spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/andaluciaSkill?ifNotExists=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456DAW.
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always


jwt.secret=VGVzdF9rZXlfc2VjdXJvX3ZhbGlkYV9lbnRyYWRhX2FkYXB0YV9leGFtcGxlX2tleQ==
jwt.expiration=3600000  







